'use client';
import { FormEvent, useMemo, useState } from 'react';
import Link from 'next/link';
import CommandSuggestions, { publicCommandSuggestions } from './command-suggestions';
type ChatMessage={from:'aegis'|'user';text:string};
type CheckResult={hostname:string;score:number;https:boolean;hsts:boolean;csp:boolean;nosniff:boolean;serverExposed:boolean};
type EmailFinding={key:string;status:'passed'|'warning'|'info';label:string;detail:string;recommendation:string};
type EmailResult={domain:string;score:number;grade:string;checkedAt:string;findings:EmailFinding[];dkim:{selector:string|null;found:boolean}};
type SecurityTool={mark:string;name:string;category:string;description:string;status:string;tone:string;docs?:string};
const securityTools:SecurityTool[]=[
 {mark:'NM',name:'Nmap',category:'Network discovery',description:'Maps exposed services and software versions on verified company systems.',status:'Runner ready',tone:'ready',docs:'https://www.kali.org/tools/nmap/'},
 {mark:'NU',name:'Nuclei',category:'Known web risks',description:'Runs curated, non-destructive checks for known website and API issues.',status:'Runner ready',tone:'ready'},
 {mark:'TS',name:'testssl.sh',category:'Encryption',description:'Reviews TLS protocols, certificates, ciphers, and encryption weaknesses.',status:'Runner ready',tone:'ready'},
 {mark:'TH',name:'theHarvester',category:'Passive OSINT',description:'Discovers public subdomains and internet-facing business assets without exploitation.',status:'Adapter ready',tone:'ready'},
 {mark:'SQ',name:'SQLMap',category:'SQL injection',description:'Performs low-risk SQL injection detection only after domain ownership and approval.',status:'Verified only',tone:'guarded'},
 {mark:'ZP',name:'OWASP ZAP',category:'Web application',description:'Provides a passive baseline review and can expand into authenticated testing later.',status:'Passive mode',tone:'guarded'},
 {mark:'BP',name:'Burp Suite',category:'Application testing',description:'Connects professional or enterprise Burp workflows through a licensed API integration.',status:'Integration',tone:'planned'},
 {mark:'JR',name:'John the Ripper',category:'Password audit',description:'Audits customer-provided hashes inside a separate offline, isolated worker.',status:'Offline worker',tone:'offline'},
 {mark:'HC',name:'Hashcat',category:'Password audit',description:'GPU-ready password-strength auditing for authorized, customer-provided hash sets.',status:'Offline worker',tone:'offline'},
 {mark:'NK',name:'Nikto',category:'Web server review',description:'Checks a verified web server for known risky files, defaults, and outdated software indicators.',status:'Verified only',tone:'guarded',docs:'https://www.kali.org/tools/nikto/'},
 {mark:'WW',name:'WhatWeb',category:'Technology discovery',description:'Identifies public website technologies so findings can be matched to the correct remediation guidance.',status:'Low intensity',tone:'ready',docs:'https://www.kali.org/tools/whatweb/'},
 {mark:'WA',name:'Wapiti',category:'Web vulnerability review',description:'Crawls a verified website with bounded settings to identify common application weaknesses.',status:'Verified only',tone:'guarded',docs:'https://www.kali.org/tools/wapiti/'},
 {mark:'GB',name:'Gobuster',category:'Content discovery',description:'Looks for unlinked website paths using a small approved wordlist and strict request limits.',status:'Verified only',tone:'guarded',docs:'https://www.kali.org/tools/gobuster/'},
 {mark:'WP',name:'WPScan',category:'WordPress security',description:'Reviews verified WordPress sites for exposed versions, components, and known security advisories.',status:'Verified only',tone:'guarded',docs:'https://www.kali.org/tools/wpscan/'},
 {mark:'WF',name:'Wafw00f',category:'Web protection discovery',description:'Detects whether a public website appears to use a web application firewall.',status:'Low intensity',tone:'ready',docs:'https://www.kali.org/tools/wafw00f/'},
 {mark:'SS',name:'SSLScan',category:'TLS configuration',description:'Summarizes supported TLS protocols and ciphers for a verified HTTPS service.',status:'Runner ready',tone:'ready',docs:'https://www.kali.org/tools/sslscan/'},
 {mark:'DB',name:'DIRB',category:'Content discovery',description:'Runs a tightly bounded directory-content review against an explicitly approved website.',status:'Verified only',tone:'guarded',docs:'https://www.kali.org/tools/dirb/'},
 {mark:'FX',name:'Feroxbuster',category:'Content discovery',description:'Performs rate-limited recursive content discovery with a shallow approved scope.',status:'Verified only',tone:'guarded',docs:'https://www.kali.org/tools/feroxbuster/'},
 {mark:'JM',name:'JoomScan',category:'Joomla security',description:'Checks a verified Joomla site for public version and component risk indicators.',status:'Verified only',tone:'guarded',docs:'https://www.kali.org/tools/joomscan/'},
];
const protectionModules=[
 {mark:'ED',name:'Endpoint Detection & Response',short:'EDR',description:'Bring endpoint alerts, device health, and response actions into one business-friendly view.',checks:['Unprotected devices','Malware alerts','Agent health'],integrations:'Microsoft Defender · CrowdStrike · SentinelOne',status:'Connector framework'},
 {mark:'ID',name:'Identity & Access Management',short:'IAM',description:'Find risky access before it becomes an incident across workforce identity providers.',checks:['MFA coverage','Inactive admins','Excess privilege'],integrations:'Microsoft Entra · Okta · Google Workspace',status:'Connector framework'},
 {mark:'EW',name:'Email & Web Security',short:'Email / Web',description:'Check spoofing protection, risky web settings, and phishing exposure for the business.',checks:['SPF / DKIM / DMARC','DNS filtering','Security headers'],integrations:'Cloudflare · Microsoft 365 · Google Workspace',status:'Live DNS scanner'},
 {mark:'BR',name:'Backup & Recovery',short:'Recovery',description:'Measure whether critical systems are backed up, isolated, and recently restore-tested.',checks:['Backup freshness','Restore-test age','Ransomware isolation'],integrations:'Veeam · AWS Backup · Azure Backup',status:'Posture module'},
 {mark:'CH',name:'Cyber Hygiene Scanner',short:'Hygiene',description:'Combine website, network, identity, endpoint, email, patch, and backup signals into one score.',checks:['External exposure','Core controls','Fix priorities'],integrations:'Aegis composite assessment',status:'Composite scanner'},
];
const nextIdeas=[['SC','Semgrep','Find insecure patterns in source code before deployment.'],['TR','Trivy','Scan containers, dependencies, and infrastructure files.'],['GL','Gitleaks','Detect exposed secrets before they reach production.'],['OS','OSV-Scanner','Identify vulnerable open-source packages and fixes.'],['SI','SIEM connection','Correlate alerts from every security source.'],['CP','Cloud posture','Check AWS, Azure, and Cloudflare configuration risk.']];
function normalizeWebsite(value:string){const raw=value.trim();if(!raw)return null;try{const url=new URL(raw.includes('://')?raw:`https://${raw}`);return url.hostname.includes('.')?url.hostname:null}catch{return null}}
export default function Home(){
 const[url,setUrl]=useState('');const[website,setWebsite]=useState('');const[result,setResult]=useState<CheckResult|null>(null);const[checking,setChecking]=useState(false);const[complete,setComplete]=useState(false);const[question,setQuestion]=useState('');const[messages,setMessages]=useState<ChatMessage[]>([]);const[error,setError]=useState('');const score=useMemo(()=>result?.score??0,[result]);
 const[emailDomain,setEmailDomain]=useState('');const[dkimSelector,setDkimSelector]=useState('');const[emailResult,setEmailResult]=useState<EmailResult|null>(null);const[emailChecking,setEmailChecking]=useState(false);const[emailError,setEmailError]=useState('');
 async function startCheck(event:FormEvent){event.preventDefault();const host=normalizeWebsite(url);if(!host){setError('Enter a valid business website, such as example.com.');return}setWebsite(host);setError('');setComplete(false);setChecking(true);setMessages([]);try{const response=await fetch('/api/public-check',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url:host})});const data=await response.json();if(!response.ok)throw new Error(data.error??'The website could not be reviewed.');setResult(data);setComplete(true)}catch(caught){setWebsite('');setError(caught instanceof Error?caught.message:'The website could not be reviewed.')}finally{setChecking(false)}}
 function ask(text:string){const lower=text.toLowerCase();let reply='The most important next step is enabling HSTS and confirming every page redirects to HTTPS. Your web or hosting team can usually make this change without affecting customers.';if(lower.includes('explain')||lower.includes('hsts'))reply='HSTS is a browser safety rule that tells visitors to use only encrypted HTTPS connections. Enabling the Strict-Transport-Security response header helps prevent someone from downgrading a visitor to an unsafe connection.';else if(lower.includes('draft')||lower.includes('web-team'))reply='Here’s a concise handoff: “Please enable the Strict-Transport-Security header across the site, confirm all HTTP traffic redirects to HTTPS, and let me know when it is ready for another Aegis check.”';else if(lower.includes('score'))reply=`Your score of ${score}/100 is a prioritization aid based on the public signals Aegis could verify. It is a useful starting point, not a guarantee that the website is secure.`;else if(lower.includes('fix security')||lower.includes('headers'))reply='Start by enabling HSTS, then add a tested Content-Security-Policy and keep X-Content-Type-Options set to nosniff. Make each change in staging first so normal website features keep working.';setMessages(current=>[...current,{from:'user',text},{from:'aegis',text:reply}]);setQuestion('')}
 async function checkEmail(event:FormEvent){event.preventDefault();setEmailError('');setEmailChecking(true);try{const response=await fetch('/api/email-check',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({domain:emailDomain,dkimSelector})});const data=await response.json();if(!response.ok)throw new Error(data.error??'The email domain could not be checked.');setEmailResult(data)}catch(caught){setEmailResult(null);setEmailError(caught instanceof Error?caught.message:'The email domain could not be checked.')}finally{setEmailChecking(false)}}
 return <main className="public-site">
  <header className="public-header"><Link className="public-brand" href="/"><span>A</span><div><strong>Aegis</strong><small>Security Copilot</small></div></Link><nav><a href="#how-it-works">How it works</a><a href="#email-scanner">Email scanner</a><a href="#protection">Protection</a><a href="#tools">Tools</a></nav><div className="account-actions"><Link href="/login" className="signin-link">Sign in</Link><Link href="/signup" className="signup-button">Create free account</Link></div></header>
  <section className="hero"><div className="hero-badge"><span/> Website security, explained simply</div><h1>Is your business website<br/><em>safe right now?</em></h1><p>Enter your website and Aegis will review its public security signals, explain what matters, and help you decide what to fix next.</p>
   <div className={`chat-shell ${complete?'has-results':''}`}><div className="chat-top"><div><span className="aegis-avatar">A</span><div><strong>Aegis Security Assistant</strong><small><i/> Online · Safe public review</small></div></div><span className="encrypted">◈ Privacy protected</span></div>
    {!website&&!checking&&!complete&&<div className="starter-chat"><div className="assistant-message"><span>A</span><div><p>Hi! I can help you understand how secure your business website looks from the outside.</p><strong>What website would you like me to check?</strong></div></div><form className="url-entry" onSubmit={startCheck}><div className="url-field"><span>⌁</span><input aria-label="Business website URL" placeholder="yourbusiness.com" value={url} onChange={e=>setUrl(e.target.value)} autoCapitalize="none" autoCorrect="off"/></div><button type="submit">Check my website <span>→</span></button></form>{error&&<p className="form-error">{error}</p>}<div className="entry-notes"><span>✓ No credit card</span><span>✓ No software to install</span><span>✓ Public signals only</span></div></div>}
    {checking&&<div className="checking-state"><div className="scanner-orbit"><span>A</span><i/><b/></div><h2>Reviewing {website}</h2><p>Checking encryption, certificates, security headers, and public exposure…</p><div className="progress"><span/></div><small>This passive review does not test or exploit the website.</small></div>}
    {complete&&<div className="results-chat"><div className="result-summary"><div className="score-ring"><strong>{score}</strong><span>/100</span></div><div><span className="result-label">PUBLIC SECURITY REVIEW COMPLETE</span><h2>{website} looks generally secure</h2><p>I found two improvements worth making. Nothing suggests an immediate emergency.</p></div><span className="result-grade">Good</span></div>
     <div className="signal-grid"><Signal good={!!result?.https} title="HTTPS connection" detail={result?.https?'The site responded securely over HTTPS':'A secure HTTPS response was not confirmed'}/><Signal good={!!result?.hsts} title="HSTS protection" detail={result?.hsts?'Browser downgrade protection is enabled':'Extra browser downgrade protection is missing'}/><Signal good={!!result?.csp} title="Content security policy" detail={result?.csp?'A content security policy is present':'A content security policy was not found'}/><Signal good={!result?.serverExposed} title="Server information" detail={result?.serverExposed?'The response reveals server technology':'No server technology header was exposed'}/></div>
     <div className="ownership-gate"><div><span>◈</span><div><strong>Own this website?</strong><p>Verify the domain to unlock active checks, 24/7 monitoring, history, and email alerts.</p></div></div><a href="/signup?returnTo=%2Fdashboard">Verify & monitor this site →</a></div>
     <div className="conversation">{messages.length===0&&<div className="assistant-message compact"><span>A</span><div><p>{result?.hsts?'Your public security headers look healthy. Verify ownership to unlock deeper checks and ongoing change detection.':'I’d fix the missing HSTS protection first. Want me to explain why, or show you what to send your web team?'}</p></div></div>}{messages.map((message,index)=><div key={index} className={`bubble ${message.from}`}><span>{message.from==='aegis'?'A':'You'}</span><p>{message.text}</p></div>)}</div><CommandSuggestions className="public-command" value={question} onChange={setQuestion} onSubmit={ask} suggestions={publicCommandSuggestions} placeholder="Ask what this means or type / for commands…" buttonLabel="Ask"/><button className="check-another" onClick={()=>{setWebsite('');setComplete(false);setResult(null);setUrl('')}}>← Check another website</button>
    </div>}
   </div><div className="trust-line"><span>Designed for business owners, IT teams, and agencies</span><div><b>NMAP</b><b>NUCLEI</b><b>SQLMAP</b><b>ZAP</b><b>HASHCAT</b></div></div>
  </section>
  <section id="how-it-works" className="explain-section"><span className="section-kicker">HOW IT WORKS</span><h2>From unknown risk to clear next steps</h2><div className="steps"><article><span>01</span><h3>Enter your website</h3><p>Start with a safe review of public security signals. No account is required.</p></article><article><span>02</span><h3>Understand the results</h3><p>Aegis translates technical findings into plain business impact and priorities.</p></article><article><span>03</span><h3>Verify and monitor</h3><p>Prove ownership to unlock deeper checks, continuous monitoring, and alerts.</p></article></div></section>
  <section id="protection" className="monitor-promo"><div><span className="section-kicker light">CONTINUOUS PROTECTION</span><h2>Your website changes.<br/>Your protection should too.</h2><p>Aegis can recheck verified websites on a schedule and notify your team when a new risk appears or a certificate approaches expiry.</p><ul><li>Scheduled website and encryption checks</li><li>Configurable notification destinations</li><li>Clear history and remediation tracking</li></ul><a href="/signup?returnTo=%2Fdashboard">Create your monitoring workspace →</a></div><div className="monitor-card"><div className="monitor-head"><span className="pulse-dot"/><div><strong>Monitoring active</strong><small>staging.acme.test</small></div><b>24/7</b></div><div className="heartbeat"/><div className="monitor-stats"><div><span>Last check</span><strong>4 min ago</strong></div><div><span>Next check</span><strong>In 56 min</strong></div><div><span>Open alerts</span><strong className="amber">1</strong></div></div><div className="alert-preview"><span>!</span><div><strong>Security header changed</strong><small>Notification preference matched</small></div><time>9:42 AM</time></div></div></section>
  <section id="email-scanner" className="email-scanner"><div className="email-scanner-head"><div><span className="section-kicker">EMAIL SECURITY SCANNER</span><h2>Can criminals spoof your business email?</h2><p>Check the public safeguards that protect your domain from impersonation and help legitimate messages reach customers safely.</p></div><span className="passive-pill">Passive DNS review</span></div><div className="email-checker"><div className="email-check-form"><span>EM</span><h3>Review an email domain</h3><p>This checks public mail configuration only. Aegis never sends an email or attempts to access a mailbox.</p><form onSubmit={checkEmail}><label>Business email domain<input required aria-label="Business email domain" placeholder="yourbusiness.com" value={emailDomain} onChange={event=>setEmailDomain(event.target.value)} autoCapitalize="none" autoCorrect="off"/></label><label>DKIM selector <small>Optional — shown in your mail provider or email headers</small><input aria-label="Optional DKIM selector" placeholder="selector1" value={dkimSelector} onChange={event=>setDkimSelector(event.target.value)} autoCapitalize="none" autoCorrect="off"/></label><button disabled={emailChecking}>{emailChecking?'Checking email safeguards…':'Scan email security →'}</button></form>{emailError&&<p className="email-form-error">{emailError}</p>}<div className="email-privacy"><span>✓ No mailbox access</span><span>✓ No messages sent</span><span>✓ Public DNS records only</span></div></div><div className="email-results">{!emailResult?<div className="email-result-empty"><div><span>✉</span><strong>Your email-security results will appear here</strong><p>Aegis checks mail routing, SPF, DMARC enforcement, MTA-STS, TLS reporting, DNSSEC, and an optional DKIM selector.</p></div></div>:<><div className="email-scoreline"><div className="email-score"><strong>{emailResult.score}</strong><small>/100</small></div><div><small>EMAIL SECURITY SCORE</small><h3>{emailResult.domain}</h3><small>Checked {new Date(emailResult.checkedAt).toLocaleString()}</small></div><span className="email-grade">{emailResult.grade}</span></div><div className="email-findings">{emailResult.findings.map(finding=><article className="email-finding" key={finding.key}><span className={finding.status}>{finding.status==='passed'?'✓':finding.status==='warning'?'!':'i'}</span><div><strong>{finding.label}</strong><small>{finding.detail}</small><small>{finding.recommendation}</small></div><b>{finding.status}</b></article>)}</div><p className="email-disclaimer">This is a configuration review, not a guarantee of deliverability or protection. Verify changes with your email provider before enforcing new policies.</p></>}</div></div></section>
  <section id="tools" className="tools-catalog"><div className="catalog-heading"><div><span className="section-kicker">AEGIS TOOLKIT</span><h2>{securityTools.length} security tools. One clear conversation.</h2><p>Aegis chooses the right tool, explains what it will do, and asks for approval before any active check.</p></div><span className="conference-pill">PIT / SteelHacks build</span></div><div className="catalog-legend"><span><i className="ready"/> Runner ready</span><span><i className="guarded"/> Verified domains only</span><span><i className="offline"/> Isolated offline worker</span><span><i className="planned"/> External integration</span></div><div className="catalog-grid">{securityTools.map(tool=><article key={tool.name}><div className="catalog-top"><b>{tool.mark}</b><span className={`catalog-status ${tool.tone}`}>{tool.status}</span></div><small>{tool.category}</small><h3>{tool.name}</h3><p>{tool.description}</p>{tool.docs&&<a className="tool-docs" href={tool.docs} target="_blank" rel="noreferrer">Official Kali documentation ↗</a>}</article>)}</div><div className="tool-safety"><span>◈</span><div><strong>Safety policy travels with every tool</strong><p>Public visitors receive passive checks. Nmap, SQL injection testing, and active web checks require a verified domain, an allowlist, written authorization, and explicit approval. John the Ripper and Hashcat never touch a live website.</p></div></div></section>
  <section id="coverage" className="coverage-section"><div className="coverage-heading"><div><span className="section-kicker">WHOLE-BUSINESS PROTECTION</span><h2>More than a website scanner</h2><p>Aegis brings the five security areas most small businesses need into one clear posture view.</p></div><div className="hygiene-score"><span>Cyber hygiene</span><strong>78</strong><small>/100 · Good foundation</small></div></div><div className="module-grid">{protectionModules.map((module,index)=><article key={module.name} className={index===4?'featured':''}><div className="module-top"><span>{module.mark}</span><b>{module.status}</b></div><small>{module.short}</small><h3>{module.name}</h3><p>{module.description}</p><ul>{module.checks.map(check=><li key={check}>✓ {check}</li>)}</ul><div className="module-footer"><span>Connects with</span><strong>{module.integrations}</strong></div></article>)}</div><div className="hygiene-breakdown"><div><strong>Your hygiene assessment</strong><span>Example conference workspace</span></div><ol><li><span>Website & network</span><b>82</b><i><em style={{width:'82%'}}/></i></li><li><span>Endpoints</span><b>76</b><i><em style={{width:'76%'}}/></i></li><li><span>Identity</span><b>71</b><i><em style={{width:'71%'}}/></i></li><li><span>Email & web</span><b>88</b><i><em style={{width:'88%'}}/></i></li><li><span>Backup readiness</span><b>73</b><i><em style={{width:'73%'}}/></i></li></ol><a href="/signup?returnTo=%2Fdashboard">Run a complete hygiene assessment →</a></div></section>
  <section id="conference" className="conference-section"><div className="conference-copy"><span className="section-kicker light">CONFERENCE ROADMAP</span><h2>Strong next features for the PIT / SteelHacks pitch</h2><p>These additions broaden Aegis from website scanning into a full small-business security platform.</p></div><div className="idea-grid">{nextIdeas.map(idea=><article key={idea[1]}><span>{idea[0]}</span><div><strong>{idea[1]}</strong><p>{idea[2]}</p></div><button aria-label={`Add ${idea[1]} to roadmap`}>＋</button></article>)}</div><div className="pitch-strip"><div><span>01</span><strong>Discover</strong><small>What is exposed?</small></div><i>→</i><div><span>02</span><strong>Understand</strong><small>Why does it matter?</small></div><i>→</i><div><span>03</span><strong>Fix</strong><small>What should we do?</small></div><i>→</i><div><span>04</span><strong>Monitor</strong><small>Did anything change?</small></div></div></section>
  <footer><Link className="public-brand" href="/"><span>A</span><div><strong>Aegis</strong><small>Security Copilot</small></div></Link><p>Authorized security checks. Clear answers. Safer businesses.</p><div><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/acceptable-use">Authorized use</Link><Link href="/login">Sign in</Link></div></footer>
 </main>
}
function Signal({good,title,detail}:{good:boolean;title:string;detail:string}){return <article><span className={`signal-icon ${good?'good':'warn'}`}>{good?'✓':'!'}</span><div><strong>{title}</strong><small>{detail}</small></div><b className={good?'':'warn-text'}>{good?'Passed':'Improve'}</b></article>}
