type DnsAnswer={name:string;type:number;TTL:number;data:string};
type DnsResponse={Status:number;AD:boolean;Answer?:DnsAnswer[]};

function cleanDomain(value:string){try{const url=new URL(value.includes('://')?value:`https://${value}`);const domain=url.hostname.toLowerCase().replace(/\.$/,'');if(!domain.includes('.')||domain==='localhost'||domain.length>253||/^\d{1,3}(\.\d{1,3}){3}$/.test(domain)||!domain.split('.').every(label=>/^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/i.test(label)))return null;return domain}catch{return null}}
function cleanSelector(value:unknown){if(typeof value!=='string'||!value.trim())return null;const selector=value.trim().toLowerCase();return /^[a-z0-9][a-z0-9_-]{0,62}$/.test(selector)?selector:null}
function txtValue(answer:DnsAnswer){return answer.data.replace(/^"|"$/g,'').replace(/"\s*"/g,'')}
async function query(name:string,type:'MX'|'TXT'){const endpoint=new URL('https://dns.google/resolve');endpoint.searchParams.set('name',name);endpoint.searchParams.set('type',type);endpoint.searchParams.set('do','1');endpoint.searchParams.set('edns_client_subnet','0.0.0.0/0');const response=await fetch(endpoint,{headers:{accept:'application/json'},signal:AbortSignal.timeout(6500)});if(!response.ok)throw new Error('DNS provider did not respond');const data=await response.json() as DnsResponse;return{status:data.Status,dnssec:!!data.AD,answers:data.Answer??[]}}

export async function POST(request:Request){
 const contentLength=Number(request.headers.get('content-length')??'0');if(contentLength>4096)return Response.json({error:'Request is too large'},{status:413});
 const body=await request.json() as {domain?:unknown;dkimSelector?:unknown};const domain=cleanDomain(typeof body.domain==='string'?body.domain:'');if(!domain)return Response.json({error:'Enter a valid public business domain'},{status:400});const selector=cleanSelector(body.dkimSelector);if(typeof body.dkimSelector==='string'&&body.dkimSelector.trim()&&!selector)return Response.json({error:'The DKIM selector contains unsupported characters'},{status:400});
 try{
  const [mx,rootTxt,dmarc,mtaSts,tlsRpt,dkim]=await Promise.all([query(domain,'MX'),query(domain,'TXT'),query(`_dmarc.${domain}`,'TXT'),query(`_mta-sts.${domain}`,'TXT'),query(`_smtp._tls.${domain}`,'TXT'),selector?query(`${selector}._domainkey.${domain}`,'TXT'):Promise.resolve(null)]);
  const rawMxRecords=mx.answers.filter(answer=>answer.type===15).map(answer=>answer.data.trim());const nullMx=rawMxRecords.some(record=>/^0\s+\.$/.test(record));const mxRecords=rawMxRecords.filter(record=>!/^0\s+\.$/.test(record));const mailRoutingConfigured=mxRecords.length>0||nullMx;const rootRecords=rootTxt.answers.filter(answer=>answer.type===16).map(txtValue);const dmarcRecords=dmarc.answers.filter(answer=>answer.type===16).map(txtValue);const mtaStsRecords=mtaSts.answers.filter(answer=>answer.type===16).map(txtValue);const tlsRptRecords=tlsRpt.answers.filter(answer=>answer.type===16).map(txtValue);const dkimRecords=dkim?.answers.filter(answer=>answer.type===16).map(txtValue)??[];
  const spf=rootRecords.find(record=>record.toLowerCase().startsWith('v=spf1'))??null;const dmarcRecord=dmarcRecords.find(record=>record.toLowerCase().startsWith('v=dmarc1'))??null;const dmarcPolicy=dmarcRecord?.match(/(?:^|;)\s*p\s*=\s*(none|quarantine|reject)/i)?.[1].toLowerCase()??null;const mtaStsRecord=mtaStsRecords.find(record=>record.toLowerCase().startsWith('v=stsv1'))??null;const tlsRptRecord=tlsRptRecords.find(record=>record.toLowerCase().startsWith('v=tlsrptv1'))??null;const dkimRecord=dkimRecords.find(record=>/\bv\s*=\s*dkim1\b/i.test(record)||/\bp\s*=/i.test(record))??null;
  let score=0;if(mailRoutingConfigured)score+=15;if(spf)score+=20;if(spf&&/(?:^|\s)-all(?:\s|$)/i.test(spf))score+=5;if(dmarcRecord)score+=25;if(dmarcPolicy==='quarantine'||dmarcPolicy==='reject')score+=15;if(mtaStsRecord)score+=10;if(tlsRptRecord)score+=5;if(mx.dnssec)score+=5;
  const findings=[
   {key:'mx',status:mailRoutingConfigured?'passed':'warning',label:'Mail routing (MX)',detail:nullMx?'The domain explicitly declares that it does not receive email.':mxRecords.length?`${mxRecords.length} mail server record${mxRecords.length===1?'':'s'} found.`:'No MX mail-routing record was found.',recommendation:nullMx?'Keep the null MX record if this domain should never receive mail.':mxRecords.length?'Confirm every listed provider is expected.':'Add an MX record if this domain should receive email.'},
   {key:'spf',status:spf?'passed':'warning',label:'SPF sender policy',detail:spf?(spf.length>180?`${spf.slice(0,177)}…`:spf):'No SPF record was found.',recommendation:spf?'Review included services and remove senders the business no longer uses.':'Publish one SPF record listing every approved email sender.'},
   {key:'dmarc',status:dmarcPolicy==='reject'||dmarcPolicy==='quarantine'?'passed':dmarcRecord?'warning':'warning',label:'DMARC protection',detail:dmarcRecord?`Policy: ${dmarcPolicy??'not specified'}`:'No DMARC record was found.',recommendation:dmarcPolicy==='reject'||dmarcPolicy==='quarantine'?'Continue reviewing DMARC reports for legitimate delivery issues.':dmarcRecord?'Move from monitoring toward quarantine or reject after validating legitimate senders.':'Start with a monitored DMARC policy, review reports, then enforce it.'},
   {key:'mta-sts',status:mtaStsRecord?'passed':'info',label:'Inbound TLS policy (MTA-STS)',detail:mtaStsRecord?'An MTA-STS DNS policy marker is published.':'No MTA-STS policy marker was found.',recommendation:mtaStsRecord?'Confirm the HTTPS policy file is current.':'Consider MTA-STS to require encrypted delivery from supporting senders.'},
   {key:'tls-rpt',status:tlsRptRecord?'passed':'info',label:'TLS reporting',detail:tlsRptRecord?'SMTP TLS reporting is configured.':'SMTP TLS reporting was not detected.',recommendation:tlsRptRecord?'Monitor the reporting destination for delivery failures.':'Add TLS-RPT alongside MTA-STS for visibility into transport failures.'},
   {key:'dnssec',status:mx.dnssec?'passed':'info',label:'DNSSEC validation',detail:mx.dnssec?'The MX response validated with DNSSEC.':'DNSSEC validation was not confirmed for the MX response.',recommendation:mx.dnssec?'Maintain DNSSEC during DNS-provider changes.':'Ask the DNS provider whether DNSSEC can be enabled.'},
   {key:'dkim',status:selector?(dkimRecord?'passed':'warning'):'info',label:'DKIM signature key',detail:selector?(dkimRecord?`A public key was found for selector “${selector}”.`:`No public key was found for selector “${selector}”.`):'Enter a selector to verify a specific DKIM key.',recommendation:selector?(dkimRecord?'Rotate signing keys according to the mail provider’s guidance.':'Confirm the selector in a recent signed message or mail-provider settings.'):'DKIM selectors are provider-specific and cannot be reliably guessed.'},
  ];
  return Response.json({domain,score,grade:score>=85?'Strong':score>=65?'Good':score>=40?'Needs work':'High risk',checkedAt:new Date().toISOString(),mxRecords,nullMx,spf,dmarc:{record:dmarcRecord,policy:dmarcPolicy},mtaSts:!!mtaStsRecord,tlsReporting:!!tlsRptRecord,dnssec:mx.dnssec,dkim:{selector,found:!!dkimRecord},findings});
 }catch{return Response.json({error:'Email DNS records could not be checked right now. Try again shortly.'},{status:502})}
}
